name: petshop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  auto_size_text: ^3.0.0
  cloud_firestore: ^4.3.2
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dropdown_search: ^5.0.5
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  firebase_core_platform_interface: ^4.5.3
  firebase_storage: ^11.0.11
  firebase_storage_web: ^3.3.6
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: 5.4.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.6.1
  focused_menu: ^1.0.5
  font_awesome_flutter: ^10.4.0
  footer: ^0.0.4
  form_field_validator: ^1.1.0
  geolocator: any
  get: 4.6.5
  hexcolor: ^3.0.1
  iconly: ^1.0.1
  syncfusion_localizations: ^20.4.49

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/images/
uses-material-design: true
